magefiles:
  container_name: magefiles
  image: busybox
  volumes:
    - "./src:/var/www/html"
magesql:
  container_name: magesql
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass123
    - MYSQL_DATABASE=magento
    - MYSQL_USER=magento
  volumes:
    - "./mysql/my.cnf:/etc/mysql/my.cnf"
    - "./mysql/log:/var/log/mysql"
magephp:
  build: .
  container_name: magephp
  links:
    - "magesql:sqlserver"
  volumes_from:
    - magefiles
magenginx:
  container_name: magenginx
  image: nginx
  links:
    - "magephp:phpfpmserver"
    - "magesql:sqlserver"
  volumes:
    - ./nginx:/etc/nginx
  volumes_from:
    - magefiles
  ports:
    - "5000:80"
    - "5001:443"
