magefiles:
  container_name: magefiles
  image: busybox
  volumes:
    - "./src:/var/www/html"
mysqlfiles:
  container_name: mysqlfiles
  image: busybox
  volumes:
    - "./mysql/conf.d:/var/log/mysql/conf.d"
    - "./mysql/log:/var/log/mysql"
    - "./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
nginxfiles:
  container_name: nginxfiles
  image: busybox
  volumes:
    - ./nginx:/etc/nginx
magesql:
  container_name: magesql
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass123
    - MYSQL_DATABASE=magento
  volumes_from:
    - mysqlfiles
magephp:
  build: .
  container_name: magephp
  links:
    - "magesql:sqlserver"
  volumes_from:
    - magefiles
magenginx:
  container_name: magenginx
  image: nginx
  links:
    - "magephp:phpfpmserver"
    - "magesql:sqlserver"
  volumes_from:
    - magefiles
    - nginxfiles
  ports:
    - "5000:80"
    - "5001:443"
